version: '3'

services:
  esearch:
      container_name: elasticsearch
      build: elasticsearch/
      volumes:
        - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        - "cluster.name=elasticsearch"
        - "network.host=0.0.0.0"
        - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
        - "XPACK_SECURITY_ENABLED=false"

  interface:
    container_name: interface
    build: ./interface
    restart: always
    links:
      - esearch
    depends_on:
      - esearch
